style:
  fonts:
    - &default_font Hack Nerd Font:pixelsize=12
    - &bold_font    Hack Nerd Font:pizelsize=12:style:Bold
    - &tag_font     Hack Nerd Font:pixelsize=14:style:Bold

  colors:
    - &accent     6dcae8ff
    - &disabled   fb167eff
    - &text       e1e3e4ff
    - &bg         2b2d3aff



  opts:

    - &margin_base
        left-margin:  5
        right-margin: 5

    - &label_base
        <<:         *margin_base
        font:       *bold_font
        foreground: *bg
        deco: {background: {color: *accent}}

    - &string_base
        font:       *default_font
        <<:         *margin_base

    - &bar_base
        height:     24
        location:   top
        spacing:    2
        margin:     0
        background: *bg
        foreground: *text

    - river_opts:
        - &river_base
            left-margin: 10
            right-margin: 10
            conditions:
              id == 1: {string: {text: "{id}", font: *tag_font}} 
              id == 2: {string: {text: "{id}", font: *tag_font}} 
              id == 3: {string: {text: "{id}", font: *tag_font}} 
              id == 4: {string: {text: "{id}", font: *tag_font}} 
              id == 5: {string: {text: "{id}", font: *tag_font}} 
              id == 6: {string: {text: "{id}", font: *tag_font}} 
              id == 7: {string: {text: "{id}", font: *tag_font}} 
              id == 8: {string: {text: "{id}", font: *tag_font}} 
              id == 9: {string: {text: "{id}", font: *tag_font}} 
        - tag_styles:
            - &focused
                foreground: *bg
                deco:
                  background:
                    color:  *accent

            - &unfocused
                deco:
                  border:
                    size:   3 
                    color:  *accent

            - &occupied
                deco:
                  underline:
                    size:   3 
                    color:  *accent



modules:

    - &river
        content:
          map:
            conditions:
              state == focused:
                map:
                  <<: [*river_base, *focused]
              state == unfocused:
                map:
                  <<: [*river_base, *unfocused]
              state == invisible && ~occupied:
                map: 
                  <<: *river_base
              state == invisible && occupied:
                map:
                  <<: [*river_base, *occupied]

    - &cpu
        poll-interval: 2500
        content:
          map:
            conditions:
              id == -1: 
                - string: 
                    text: "CPU"
                    <<: *label_base
                - string: 
                    text: "{cpu}%"
                    <<: *string_base

    - &mem
        poll-interval: 2500
        content:
          - string:
              text: "MEM"
              <<: *label_base
          - string:
              text: "{used:mb}MB"
              <<: *string_base

    - &clock
        content:
          - string:
              text: "TIME"
              <<: *label_base
          - string:
              text: "{date}"
              <<: *string_base
          - string:
              text: "{time}"
              <<: *string_base
